INSERT INTO movie (
    duration, is_showing, language, large_imageurl, long_description, name, rated, release_date, short_description,
    small_imageurl, trailerurl_watch_link, format, director_id, categories, [views]
) VALUES
(105, 1, N'Tiếng Anh với phụ đề tiếng Việt và lồng tiếng Việt', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/r/s/rsz_dr-strange-980x448.jpg',
 N'Nhóc trùm Ted giờ đây đã trở thành một triệu phú nổi tiếng trong khi Tim lại có một cuộc sống đơn giản bên vợ anh Carol và hai cô con gái nhỏ yêu dấu. Mỗi mùa Giáng sinh tới, cô Tina và Tabitha đều mong được gặp chú Ted nhưng dường như hai anh em nhà Templeton nay đã không còn gần gũi như xưa. Nhưng bất ngờ thay khi Ted lại có màn tái xuất không thể hoành tráng hơn khi đáp thẳng máy bay trực thăng tới nhà Tim trước sự ngỡ ngàng của cả gia đình.',
 N'Nhóc Trùm: Nổi Nghiệp Gia Đình', N'P - PHIM DÀNH CHO MỌI ĐỐI TƯỢNG', '2021-12-24',
 N'Nhóc trùm Ted giờ đây đã trở thành một triệu phú nổi tiếng trong khi Tim lại có một cuộc sống đơn giản bên vợ anh Carol và hai cô con gái nhỏ yêu dấu. Mỗi mùa Giáng sinh tới, cô Tina và Tabitha đều mong được gặp chú Ted',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_boss_baby_2_24.12.2021_1_1_1__1.jpg',
 'https://www.youtube.com/watch?v=Lv8nL2q8yRI', '3D,IMAX 3D', 1, N'Hành động', 1),

(100, 1, N'Tiếng Anh - Phụ đề Tiếng Việt', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/b/l/blackpink-rolling_1_.jpg',
 N'Siêu bom tấn #VENOM: LET THERE BE CARNAGE hứa hẹn trận chiến khốc liệt nhất giữa Venom và kẻ thù truyền kiếp, Carnage.',
 N'Venom: Đại Mặt Tử Thù', N'C13 - PHIM CẤM KHÁN GIẢ DƯỚI 13 TUỔI', '2021-12-10',
 N'Siêu bom tấn #VENOM: LET THERE BE CARNAGE hứa hẹn trận chiến khốc liệt nhất giữa Venom và kẻ thù truyền kiếp, Carnage.',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_venom_121121_1__1.jpg',
 'https://www.youtube.com/watch?v=EVWdzVtSh1I', '3D,IMAX 3D', 2, N'Hành động', 2),

(148, 1, N'Tiếng Anh - Phụ đề Tiếng Việt, Phụ đề Tiếng Hàn', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/b/l/blackpink-rolling_1_.jpg',
 N'Ma Trận: Hồi Sinh là phần phim tiếp theo rất được trông đợi của loạt phim “Ma Trận” đình đám, đã góp phần tái định nghĩa thể loại phim khoa học viễn tưởng. Phần phim mới nhất này đón chào sự trở lại của cặp đôi Keanu Reeves và Carrie-Anne Moss với vai diễn biểu tượng đã làm nên tên tuổi của họ, Neo và Trinity. Ngoài ra, phim còn có sự góp mặt của dàn diễn viên đầy tài năng gồm Yahya Abdul-Mateen II, Jessica Henwick, Jonathan Groff, Neil Patrick Harris, Priyanka Chopra Jonas và Christina Ricci.',
 N'Ma Trận: Hồi Sinh', N'C18 - PHIM CẤM KHÁN GIẢ DƯỚI 18 TUỔI', '2021-12-24',
 N'Sau 20 năm, siêu phẩm ma trận đã trở lại với người xem, Neo is back! Liệu đây có phải phần kết cho franchise này',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_matrix_4_1__1.jpg',
 'https://www.youtube.com/watch?v=l2UTOJC5Tbk', '3D,IMAX 3D', 3, N'Hành động', 3),

(96, 1, N'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/d/o/doreamon.jpg',
 N'Một ngày nọ, Nobita vô tình tìm thấy chú gấu bông cũ, món đồ chơi chất chứa bao kỷ niệm cùng người bà đáng kính. Với khát khao “muốn gặp bà lần nữa”, Nobita đã trở về quá khứ bằng cỗ máy thời gian, bất chấp sự phản đối của Doraemon. Dù ngạc nhiên, bà vẫn tin cậu thiếu niên lớn tưởng trước mặt mình là cháu mình. Trước nguyện vọng tha thiết “mong được thấy cháu đâu một lần”, chuyến phiêu lưu của Doraemon và Nobita bắt đầu. Nobita muốn cho bà xem đám cưới của mình, nhưng đúng ngày thành hôn với Shizuka, chú rể Nobita lại trên một Jaian và Suneo chạy dôn chạy đáo tìm bạn, còn Shizuka vẫn tin tưởng chờ đợi Nobita. Để thực hiện nguyện vọng của bà, đáp lại niềm tin của gia đình, bạn bè và Shizuka yêu quý, Nobita sẽ cùng Doraemon du hành vượt thời gian. Họ sẽ mang đến cho chúng ta một câu chuyện cảm động đến rơi lệ về quan hệ con người, kết nối giữa quá khứ, hiện tại và tương lai.',
 N'Doraemon: Ôi Bạn Ơi 2', N'P - PHIM DÀNH CHO MỌI ĐỐI TƯỢNG', '2024-05-27',
 N'Một ngày nọ, Nobita vô tình tìm thấy chú gấu bông cũ, món đồ chơi chất chứa bao kỷ niệm cùng người bà đáng kính. Với khát khao “muốn gặp bà lần nữa”, Nobita đã trở về quá khứ bằng cỗ máy thời gian, bất chấp sự phản đối của Doraemon',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_doremon_2_1__1.jpg',
 'https://www.youtube.com/watch?v=GXnOs4Hj8MA', '3D,IMAX 3D', 4, N'Hài', 50),

(156, 0, N'Tiếng Anh - Phụ đề Tiếng Việt', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/w/s/wss_sneak_980x448.jpg',
 N'Được đạo diễn bởi đạo diễn gạo cội từng giành giải Oscar Steven Spielberg, cùng kịch bản bởi biên kịch từng giành giải Pulitzer Prize và giải Tony Award, Tony Kushner, “Câu chuyện phía Tây” kể lại câu chuyện tình yêu kinh điển của Tony và Maria, giữa sự giằng xé của tình yêu trẻ tuổi và sự ngăn cấm, thù hận ở thành phố New York những năm 1950.',
 N'Câu Chuyện Phía Tây', N'C16 - PHIM CẤM KHÁN GIẢ DƯỚI 16 TUỔI', '2021-12-24',
 N'“Câu chuyện phía Tây” kể lại câu chuyện tình yêu kinh điển của Tony và Maria, giữa sự giằng xé của tình yêu trẻ tuổi và sự ngăn cấm, thù hận ở thành phố New York những năm 1950',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_wss_1200x1800__1.jpg',
 'https://www.youtube.com/watch?v=QPvqV71P0Fo', '3D,IMAX 3D', 5, N'Nhạc kịch', 5),

(99, 0, N'Tiếng Hàn - Phụ đề tiếng Việt', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/b/l/blackpink-rolling_1_.jpg',
 N'Nhóm nhạc nữ được yêu thích toàn cầu, BLACKPINK sẽ kỷ niệm năm thứ 5 hoạt động của nhóm với việc phát hành BLACKPINK THE MOVIE, đây cũng như là món quà đặc biệt dành tặng cho các BLINK— fandom của BLACKPINK — bộ phim sẽ tái hiện một cách sống động những kỷ niệm không thể quên cùng những màn trình diễn đầy cuồng nhiệt đúng tinh thần lễ hội.',
 N'BlackPink The Movie', N'P - PHIM DÀNH CHO MỌI ĐỐI TƯỢNG', '2021-12-24',
 N'Nhóm nhạc nữ được yêu thích toàn cầu, BLACKPINK sẽ kỷ niệm năm thứ 5 hoạt động của nhóm với việc phát hành BLACKPINK THE MOVIE',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/p/o/poster_blackpink_vie_2_1__1.jpg',
 'https://www.youtube.com/watch?v=Q_rK9UlUN-Q', '3D,IMAX 3D', 6, N'Phim tài liệu', 6),

(149, 1, N'Tiếng Anh - Phụ đề Tiếng Việt', 'https://www.cgv.vn/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/r/s/rsz_dr-strange-980x448.jpg',
 N'Lần đầu tiên trong lịch sử điện ảnh của Người Nhện, thân phận người hàng xóm thân thiện bị lật mở, khiến trách nhiệm làm một Siêu Anh Hùng xung đột với cuộc sống bình thường và đặt người anh quan tâm nhất vào tình thế nguy hiểm. Khi anh nhận được giúp đỡ của Doctor Strange để khôi phục lại bí mật, phép thuật đã gây ra lỗi hỏng thời không, giải phóng những ác nhân mạnh mẽ nhất từng đối đầu với Người Nhện từ mọi vũ trụ. Bây giờ, Peter sẽ phải vượt qua thử thách lớn nhất của mình, nó sẽ thay đổi không chỉ tương lai của chính anh mà còn là tương lai của cả Đa Vũ Trụ.',
 N'Người Nhện: Không Còn Nhà', N'C13 - PHIM CẤM KHÁN GIẢ DƯỚI 13 TUỔI', '2021-12-17',
 N'Đa vũ trụ được mở ra, những kẻ phản diện nào sẽ trảm chán spidey, cùng đón xem nhé',
 'https://www.cgv.vn/media/catalog/product/cache/1/small_image/240x388/dd828b13b1cb77667d034d5f59a82eb6/s/n/snwh_poster_bluemontage_4x5fb_1__1.jpg',
 'https://www.youtube.com/watch?v=daHCu_jU5mQ', '3D,IMAX 3D', 7, N'Hành động', 7),

(120, 1, N'English', 'https://cdn.moveek.com/storage/media/cache/short/657927b0a2639977829433.jpeg',
 N'Nam về quê để lo đám tang cho bố sau cái chết kinh hoàng của ông, trong khi phải che giấu bạn gái đang mang thai. Nam mơ thấy gia đình bị giết sau khi mai táng bố, và Mít – con chó trông của gia đình có biểu hiện kỳ lạ. Ông Quyết, bà Thúy, và bà Liễu thì tin vào thầy cúng, còn Nam nghi ngờ về lò mổ chó truyền thống của gia đình và phải điều tra để giải quyết sự kiện kỳ lạ đang diễn ra.',
 N'Quỷ cẩu', '18', '2025-02-13',
 N'- Horror', 'https://cdn.moveek.com/storage/media/cache/short/657927b0a2639977829433.jpeg',
 'https://www.youtube.com/watch?v=m1yZFJ1ykw4', '3D,IMAX 3D', 8, N'Kinh dị', 8);


 INSERT INTO [SWP391].[dbo].[director] ([name], [description])
VALUES
('John Smith', NULL),
('Andy Serkis', NULL),
('Lana Wachowski', NULL),
('Takashi Yamazaki', NULL),
('Quentin Tarantino', NULL),
('Park Jun-soo', NULL),
('Jon Watts', NULL),
('Luu Thành Luân', NULL);


INSERT INTO [SWP391].[dbo].[event] (
    [name], [description], [start_date], [end_date], [branch_id], [movie_id], [image_url], [status]
) VALUES
(N'Uu đãi khởi nghỉ hè', N'Uu đãi khởi nghỉ hè combo 39k gồm 1 bắp + 1 nước dành cho nhóm 20 trẻ trở lên', '2025-06-01 14:30:00', '2025-06-30 14:30:00', NULL, NULL, 'https://files.betacorp.vn/media/images/2025/05/10/don-khoi-nghi-he-900-x-900-copy-3-1702-x-621-182625-100525-68.png', 1),
(N'Combo Cung chiếu', N'Các em bé xem phim tại rạp sẽ được mua combo em bé', '2025-05-31 14:30:00', '2025-06-30 14:30:00', NULL, NULL, 'https://files.betacorp.vn/media/images/2025/05/30/ctkm-em-be-45k-1702-x-621-182448-300525-12.png', 1),
(N'Tặng bội mùa hè quạt tay kèm charm', N'Tặng bội mùa hè quạt tay kèm charm khi mua 2 vé xem phim suất chiều sớm', '2025-05-31 14:30:00', '2025-06-30 14:30:00', NULL, NULL, 'https://iguov8nhvyobj.vcdn.cloud/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/d/r/drm-980x448.png', 1),
(N'Member day', N'x2 điểm thưởng và tặng bắp miễn phí vào các ngày đôi', '2025-05-31 14:30:00', '2025-06-30 14:30:00', NULL, NULL, 'https://iguov8nhvyobj.vcdn.cloud/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/9/8/980x448_9__7.jpg', 1),
(N'Tặng lượt gấp thú', N'mua hoặc nạp thẻ tặng số lượt gấp thú 200k = 2 lượt, 400k = 4 lượt, 600k = 6 lượt', '2025-05-31 14:30:00', '2025-06-30 14:30:00', NULL, NULL, 'https://iguov8nhvyobj.vcdn.cloud/media/banner/cache/1/b58515f018eb873dafa430b6f9ae0c1e/9/8/980x448-gap-thu.jpg', 1);

INSERT INTO [SWP391].[dbo].[actor] ([name]) VALUES
(N'Alec Baldwin'),
(N'James Marsden'),
(N'Amy Sedaris'),
(N'Eva Longoria'),
(N'Jeff Goldblum'),
(N'Tom Hardy'),
(N'Michelle Williams'),
(N'Woody Harrelson'),
(N'Naomie Harris'),
(N'Reid Scott'),
(N'Keanu Reeves'),
(N'Carrie-Anne Moss'),
(N'Yahya Abdul-Mateen II'),
(N'Jada Pinkett Smith'),
(N'Jessica Henwick'),
(N'Wasabi Mizuta'),
(N'Megumi Oohara'),
(N'Yumi Kakazu'),
(N'Tomokazu Seki'),
(N'Kazuya Nakai'),
(N'Ansel Elgort'),
(N'Rachel Zegler'),
(N'Ariana DeBose'),
(N'David Alvarez'),
(N'Mike Faist'),
(N'Jennie Kim'),
(N'Lisa Manoban'),
(N'Jisoo Kim'),
(N'Rosé (Roseanne Park)'),
(N'Tom Holland'),
(N'Zendaya'),
(N'Benedict Cumberbatch'),
(N'Alfred Molina'),
(N'Jamie Foxx'),
(N'Willem Dafoe'),
(N'Jacob Batalon'),
(N'Marisa Tomei'),
(N'Jon Favreau'),
(N'NSND Kim Xuân'),
(N'Quang Tuấn'),
(N'Quốc Quân'),
(N'Vân Dung'),
(N'Mie'),
(N'Nam Thu');


INSERT INTO [SWP391].[dbo].[movie_actor] (movie_id, actor_id, name_in_movie) VALUES
(4, 1, N'Theodore Templeton'),
(4, 2, N'Tim Templeton'),
(4, 3, N'Tina Templeton'),
(4, 4, N'Carla'),
(4, 5, N'Dr. Erwin Armstrong'),
(5, 6, N'Eddie Brock / Venom'),
(5, 7, N'Anne Weying'),
(5, 8, N'Cletus Kasady / Carnage'),
(5, 9, N'Shriek'),
(5, 10, N'Dan Lewis'),
(6, 11, N'Neo / Thomas Anderson'),
(6, 12, N'Trinity'),
(6, 13, N'Morpheus'),
(6, 14, N'Niobe'),
(6, 15, N'Bugs'),
(7, 16, N'Doraemon'),
(7, 17, N'Nobita Nobi'),
(7, 18, N'Shizuka Minamoto'),
(7, 19, N'Takeshi Gouda'),
(8, 21, N'Tony'),
(8, 22, N'Maria'),
(8, 23, N'Anita'),
(8, 24, N'Bernardo'),
(8, 25, N'Riff'),
(9, 26, N'Jennie'),
(9, 27, N'Lisa'),
(9, 28, N'Jisoo'),
(9, 29, N'Rosé'),
(9, 30, N'Peter Parker / Spider-Man'),
(10, 31, N'MJ'),
(10, 32, N'Doctor Strange'),
(10, 33, N'Doctor Octopus'),
(10, 34, N'Electro'),
(10, 35, N'Green Goblin'),
(10, 36, N'Ned Leeds'),
(10, 37, N'Aunt May'),
(10, 38, N'Happy Hogan'),
(11, 39, N'bà Nga'),
(11, 40, N'ông Mạnh'),
(11, 41, N'ông Tuấn'),
(11, 42, N'em gái ông Mạnh'),
(11, 43, N'nữ chính'),
(11, 44, N'nữ phụ');
